source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'
pod 'AFNetworking', '~> 2.5'
pod 'MBProgressHUD', '~> 0.9.1'
pod 'TGLStackedViewController', '~> 1.1'
pod 'AWSS3', '~> 2.2.3'
pod 'Flurry-iOS-SDK/FlurrySDK'
